// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo3M47K1tOvwXRm5KL28Z2ov51OgmntKo',
    appId: '1:547645345985:web:52998243f33293bebf4440',
    messagingSenderId: '547645345985',
    projectId: 'fady-chat-app',
    authDomain: 'fady-chat-app.firebaseapp.com',
    storageBucket: 'fady-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPVrTLULwEmcEiQS2D3HJ-6_pVrQM2saQ',
    appId: '1:547645345985:android:ad44b54fd4ce7732bf4440',
    messagingSenderId: '547645345985',
    projectId: 'fady-chat-app',
    storageBucket: 'fady-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE9OCKvZnhUqFFXXbL2ehjt1u9BIBKCYA',
    appId: '1:547645345985:ios:fd01a6e0820be9a9bf4440',
    messagingSenderId: '547645345985',
    projectId: 'fady-chat-app',
    storageBucket: 'fady-chat-app.appspot.com',
    iosBundleId: 'com.fadyfawzy.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE9OCKvZnhUqFFXXbL2ehjt1u9BIBKCYA',
    appId: '1:547645345985:ios:9dbfd249a349e749bf4440',
    messagingSenderId: '547645345985',
    projectId: 'fady-chat-app',
    storageBucket: 'fady-chat-app.appspot.com',
    iosBundleId: 'com.fadyfawzy.chatApp.RunnerTests',
  );
}
